### ISSUE TITLE
MAS

### ISSUE THREAD

**Issue by marado** [Politica-Para-Todos/pt-programas-legislativas-2019#21]
Tudo indica que esta "folha" é o programa do MAS para as legislativas:
http://mas.org.pt/images/stories/folha/folha_mas_legislativas2019.pdf

É um folheto de quarto páginas, mas é com "conteúdo programático" para as legislativas, e não me parece que haja um documento mais extenso.

**Comment by meddulla** [comment]
Não tinha visto esta issue antes mas tive a mesma dúvida e enviei-lhes email a perguntar. Caso não haja já outra pessoa interessada, posso ficar encarregue de converter para markdown o programa do MAS.

**Comment by nuno-carneiro** [comment]
Obrigado. @meddulla podes confirmar aqui assim que tenhas uma resposta pf?

**Comment by meddulla** [comment]
Sim, confirmo. Vamos ver se respondem...

**Comment by meddulla** [comment]
Eles não responderam ainda portanto acho que já não vão responder. Acho que se devia avançar com o link que o @marado sugeriu como se fosse o programa. Btw, estou disponível para fazer a conversão.

**Comment by nuno-carneiro** [comment]
Eles responderam ao nosso email ontem com o link para um folheto (deve ser o mesmo). Adicionei no README o link enviado pelo MAS. @meddulla podes então fazer a conversão e adicionar o teu nome no README? Obrigado.

**Comment by meddulla** [comment]
Sim, combinado. Faço o pull request algures nos próximos dias.
