### ISSUE TITLE
Nós, Cidadãos! Set2019

### ISSUE THREAD

**Issue by joanafloresc** [Politica-Para-Todos/pt-programas-legislativas-2019#23]
# **FUTURO INADIÁVEL**
# UM NOVO PARADIGMA PARA PORTUGAL

## **1 • CONTRA A PRECARIEDADE DE PESSOAS E ECOSSISTEMAS**
 
**Mais pelas famílias, jovens e idosos**

1. Famílias start-up. Baixar em 25% a matéria coletável do IRS para jovens casais com um filho, 35% para quem tiver dois e assim consecutivamente

2. Plano Nacional da Maternidade, Infância e Pré-Escolaridade Obrigatória

3. Plano Nacional do Envelhecimento Activo. Criar aldeias da idade maior e parcerias entre idosos e jovens

4. Estabelecimento de valor máximo para as pensões de velhice, determinando-se um valor de rendimento a partir do qual se contribui com taxa mais reduzida

5. Promover a igualdade de género como factor de coesão social, através da defesa de políticas de igualdade salarial nas empresas e organizações

6. Apoiar a diversidade de comunidades de origem estrangeira em Portugal, muitas delas de origem lusófona e cujas experiências e talentos contribuem para a economia e a cultura

7. Reforçar os apoios aos Antigos Combatentes que serviram Portugal

**Melhor Emprego**

8. Combater a precariedade decorrente de novos paradigmas de trabalho (tele-trabalho), tendo como horizonte  providenciar a todos uma vida digna

9. Criação do Plano Nacional de Emprego Jovem

10. 35 horas semanais para todos os sectores de atividade

11. Salário Mínimo Nacional igual para o Privado e Público

12. Código do Trabalho por Turnos e Estágios Profissionais

13. Fim dos contratos a termo

**Melhor Segurança Social**

14. Plafonar as Pensões Mínimas em 75% do SMN e as Máximas em 5 SMN

15. Descida de imposto mediante redução da matéria coletável no IRS

16. Aplicação de uma taxa TSV (a determinar em concertação social) sobre o volume de negócios (faturação) e o alívio proporcional da Taxa Social Única (TSU) para empregadores e empregados

**Melhor Saúde**

17. Apoiar os cuidadores informais e familiares, bem como a garantia dos direitos laborais tanto de pessoas com doença como dos seus cuidadores.

18. Extinção do IVA nos Medicamentos e Óculos Graduados de Receita Médica Obrigatória

19. Dentistas do SNS em todos os Centros de Saúde

20. Construção e Ampliação de Hospitais SNS ( Sintra, Faro, Portimão)

21. Central de Controlo de Preços Hospitalares pela média europeia

22. Fusão das Administrações Regionais de Saúde (ARS) e da Administração Central do Sistema de Saúde (ACSS), conciliando as contas pendentes com unidades de saúde e hospitalares

**Preservar os ecossistemas**
*Proteger os Habitats Naturais, a Biodiversidade, a Agro-diversidade,combatendo a desertificação dos solos e favorecendo a descarbonização da economia*

23.  Lançar Plano nacional de Centrais de dessalinização

24. Completar Plano nacional de Barragens de Rega

25. Combater o seccionamento dos rios nacionais e defender os rios livres

26. Regulamentar a exploração de minas de lítio, de modo a impedir a exploração a céu aberto

27. Regulamentar para eliminar a poluição, ruídos e emissões de CO2, em particular através de uma estratégia que nos torne em líder em emissões zero e em transporte partilhado, alimentado por eletricidade limpa e renovável

## **2 • PELA TRANSPARÊNCIA E CONTRA A CORRUPÇÃO**

28. Modificar a nomeação do Procurador Geral da República por um sistema de eleição pelos pares – Conselho Superior da Magistratura e Conselho Superior do Ministério Público – e pelo Governo e eventualmente, a AR

29. Reforçar os recursos humanos da Justiça, com magistrados, peritos residentes e funcionários judiciais especializados no combate à corrupção

30. Revisão da Legislação das custas judiciais para particulares

31. Ponderar legislação para implementar a delação premiada de atos de corrupção e de grande criminalidade que permita ao denunciante receber até 25% da multa arrecadada pelo estado

32. Rever o excesso de garantismo que existe no direito e na lei, no que concerne ao efeito suspensivo das penas e naquilo que consideramos como abuso de recursos até ao Tribunal Constitucional, criando entre outros recursos  os prazos peremptórios de julgamento

33. Pugnar pela recuperação pelo Estado dos ativos que são fruto de corrupção, exigindo transparência orçamental, nomeadamente os contratos ruinosos que são as parcerias público-privadas rodoviárias, cujos investimentos tiveram comparticipação comunitária, nunca fiscalizada.

34. Ponderar a criação de um rigoroso sistema de delação premiada de atos de corrupção e da grande criminalidade que permita ao denunciante receber até 25% da multa arrecada pelo Estado, e um programa de proteção dos denunciantes e das testemunhas.

35. Reforçar os meios adequados ao Combate à Corrupção, ao nível da orgânica e do funcionamento interno dos tribunais e a criação de tribunais especializados no crime económico, com magistrados, peritos residentes e funcionários judiciais especializados nesta área

36. Reforçar a posição constitucional do Tribunal de Contas, cujas missões de verificação da legalidade das contas públicas e de magistratura independente do Estado reclamam maior independência, mais meios e novos poderes

37. Eliminar o sigilo bancário perante a Justiça, obrigar a declaração periódica dos bancos perante a Autoridade Tributária de todos os fluxos financeiros entre o nosso país e os paraísos fiscais e proibir a utilização de numerário em pagamentos superiores a mil euros

38. Promover a criação de um departamento de auditoria interna, que promova auditorias regulares, sobretudo, às áreas de maior risco de fraude e corrupção, criando assim um Sistema de Controlo Interno na administração pública

39. Conceber uma plataforma eletrónica de promoção da transparência, que oriente o acesso gratuito, por parte dos cidadãos, às informações pretendidas sobre a gestão pública, que não sejam consideradas sigilosas por lei

40. Apoiar o reforço de medidas de combate à corrupção, ao tráfico de influências e ao branqueamento de capitais na Europa, com o estabelecimento de normas e registos comuns das identidades e atividades dos lobbies na Comissão, no Conselho e no Parlamento Europeu

41. Usar os mecanismos legislativos para fiscalizar a corrupção dominante nos processos de transferência de fundos europeus para entidades nacionais

## **3 • POR UMA ECONOMIA SUSTENTÁVEL**

**Fiscalidade equitativa**
*Os cidadãos não aceitam mais um sistema em que o Estado cobra cada vez mais e faz cada vez menos. Por isso, NÓS, CIDADÃOS! propomos:*

42. Coerência entre as regras da EU em matéria de fiscalidade, entre as constituições de cada Estado e a própria legislação fiscal de modo a que um cidadão português, vivendo em Portugal ou noutro País da União Europeia, não seja prejudicado em termos fiscais.

43. Terminar com grande parte dos regimes de exceção, isenções e benefícios fiscais das grandes empresas, orientados para entidades dos setores financeiro, energético e comunicações, e claramente contra o bem comum

44. Taxa Equitativa no IRS e abatimento do IMI até 1 SMN

45. Tributação em IRS de todos os rendimentos singulares

46. Extinção da Tributação Autónoma, Despesas Confidenciais, PEC e PC

47. Lei do Empreendedor e Código do Estágio Profissional

48. Extinção de Taxas CAES e CMES’s na factura da Electricidade e Água

49. Cobrança do IUC pelo ano da viatura

50. Dedução do IMI da habitação própria no IRS até 3 SMN

51. Fusão de Organismos Públicos e controlo de despesa dentro do Estado

52. Tribunal de Contas a julgar Casos de Gestão Danosa Pública

**Contra o sobre-endividamento**
*Chegou a hora de resgatar pessoas e empresas do sobre-endividamento. Os cidadãos não aceitam mais que sejam apenas os Bancos a ser resgatados. Por isso, NÓS, CIDADÃOS! propomos:*

53. Legislação de insolvência e de exoneração de passivo: muitos casos de sobre-endividamento familiar não possuem outra solução senão a de declaração de insolvência e de exoneração do passivo. De igual modo, deve ser reavaliada a situação dos fiadores, muitas vezes arrastados para situação de insolvência

54. Bancos sociais e éticos de resgate: tratar-se-ia da constituição de entidades, segundo o paradigma da banca social ou ética, ou bancos de resgate, com o objetivo de adquirir créditos de famílias em situação de incumprimento, desde que essas famílias fossem economicamente viáveis segundo óptica de longo prazo

55. Assumir de responsabilidades na concessão de dívida por parte das entidades bancárias e de crédito. Esta iniciativa poderia ter como base o trabalho já desenvolvido ao nível do PARI (Plano de Acção para o Risco de Incumprimento) e do PERSI (Procedimento Extrajudicial de Regularização de Situações de Incumprimento)

56. O Orçamento de Estado deve respeitar o princípio do equilíbrio das contas públicas. Os investimentos devem dispor de indicadores de avaliação, para aferir o seu retorno e a sua sustentabilidade. A ocorrência de desvios injustificados ou a violação das regras orçamentais implicam o apuramento de responsabilidades

57. Promover uma Auditoria ao Endividamento Público direto e indireto contraído nas últimas décadas, nomeadamente às Parcerias Público-Privadas (PPP), que permitirá denunciar a legitimidade das dívidas contraídas e a nulidade ou anulabilidade dos contratos

58. Consolidar os pagamentos a credores por trimestre

59. Renegociar as PPP’s rodoviárias ou substituir os titulares

60. Plano de Amortização de Dívida indexado ao crescimento do PIB

61. Dinamizar a venda interna de títulos de divida pública

**Investir na economia social de mercado**
*Portugal tem de assegurar o sucesso de uma economia circular e sustentável, aproveitando as vantagens competitivas. Chegou a hora de termos uma economia em que pessoas e empresas tenham maior liberdade de realizar os seus projectos. Por isso, NÓS, CIDADÃOS! propomos:*

62. Estimular a rede ferroviária nacional, reabrindo troços e investindo na eletrificação da rede

63. Acelerar as ligações ferroviárias à Europa,cumprindo o Plano acordado entre Portugal e Espanha na Figueira da Foz em 2004, valorizando  o  transporte de mercadorias

64. “Lei EMEL!” Reformular e uniformizar os regulamentos das empresas  municipais de parqueamento em todo o país, onde se verificam irregularidades e mesmo procedimentos inconstitucionais, como na EMEL em Lisboa

65. Desenvolver o Aeroporto de Beja como terminal de passageiros mas sobretudo como um hub de carga, dadas as excepcionais condições de operacionalidade 24 horas/dia e a ligação ao complexo portuário de Sines

66. Criar a região NUTS II Setúbal inscrita no quadro comunitário de apoio

67. Criar Empresa Pública de gestão florestal com regulamentação preventiva de incêndios

68. Criar sistema de férias pagas no interior pelas empresas no ano zero e deduzidas nos impostos no ano zero+1

69. Criar pólos de desenvolvimento no interior que fomentem Investimento e Turismo

70. Repor o sistema de benefícios fiscais à interioridade, numa lógica de investimento local, investigação e desenvolvimento tecnológico e científico, criação sustentável de postos de trabalho, produção de bens transacionáveis e captação de parcerias e investimento estrangeiro

71. Reforçar as identidades agrícolas de cada região, protegendo as diversidades florestais contra as monoculturas

72. Promover a especialização de culturas agrícolas e a denominação de origem controlada;

73. Promover a reciclagem e o uso como combustível de óleos alimentares usados e estabelecendo em cada região zonas de “emissão zero” que sirvam como plataformas de eco-regeneração, com um regime de isenção fiscal reforçado.

74. Plano Nacional de Agricultura Biológica

75. Plano Nacional de Aquacultura

76. Plano de Internacionalização de Empresas de Potencial

77. Plano Estratégico para Exportações de bens transacionáveis.

## **4 • POR UM ESTADO CAPAZ DE SE REFORMAR**

**Sistema eleitoral**

78. Reformar o âmbito e as modalidades do referendo nacional, a primeira pedra no novo edifício da cidadania

79. Criar a iniciativa popular de referendo de âmbito, regional, municipal ou de freguesia, para revogação de leis vigentes, iniciativas governativas ou mandatos políticos

80. Reduzir para 7500 o número mínimo de assinaturas para uma iniciativa legislativa de cidadãos, com o alargamento do âmbito de incidência das propostas de lei

81. Permitir candidaturas de Grupos Independentes de Cidadãos à Assembleia da República, desde que tenham uma representação nacional mínima, que evite fenómenos de caciquismo

82. Combater a Abstenção, preparando futuro sistema de Voto Eletrónico

83. Debater a criação de Eleições Legislativas durante 2 dias – Sábado e Domingo

84. Criar sistema eleitoral também com círculos uninominais mas segundo um sistema simplificado

**Estado no Território**

85. Plano Nacional de descentralização de competências centrais

86. Fusão e Criação de Câmaras Municipais por Rácio Populacional

87. Reforçar o contributo das Regiões Autónomas para a coesão nacional, na nova aposta estratégica da plataforma continental e dos recursos do mar

88. Reverter o processo da privatização de fornecimento de água, saneamento, recolha e tratamento de resíduos sólidos

**Administração pública**

89. Redução do limite máximo das adjudicações diretas para 25.000€

90. Promover horários continuados/ alargados dos serviços públicos, de modo a facilitar o acesso dos cidadãos ao Estado, no respeito pelos direitos dos funcionários públicos

91. Aprofundar as reformas dos procedimentos administrativos no licenciamento das actividades económicas, de obras e projetos em geral, assegurando uma maioria qualificada no Parlamento para a aprovação das grandes Obras Públicas, podendo promover-se consultas populares

92. Criar um departamento central de colocação de funcionários públicos, dependente do Ministério encarregue da reforma administrativa

**Portugal no Mundo**

93. Defender intransigentemente a nossa plataforma continental, no âmbito de reforço negocial dos nossos interesses estratégicos no seio da União Europeia

94. Reforçar os poderes da Autoridade Marítima Nacional, em articulação com a nossa Marinha

95. Garantir o acompanhamento da comunidade portuguesa residente na União Europeia, através das redes de associativismo, dos conselheiros das comunidades, e apoio a órgãos de comunicação social

## **5 • PELA EDUCAÇÃO, CULTURA E CIÊNCIA AO LONGO DA VIDA**
 
96. Apoiar as indústrias culturais nacionais que deveriam ser fonte de orgulho, investimento e turismo, e símbolo da sociedade pela qual aspiramos, com até 2% do OE para a cultura

97. Valorizar o ensino artístico, e musical, alargado em parceria com associações e entidades da sociedade civil

98. Manter os Museus das grandes cidades abertos 7 dias por semana

99. Criar vínculo de efectivo para professores contratados 3 anos consecutivos

100. Respeitar os 9 anos 4 meses e 2 dias de tempo de serviço letivo dos Professores com medidas semelhantes às adoptadas pelas Regiões Autónomas da Madeira e Açores

101. Legislar para que as SAD’s dos clubes de Futebol invistam 5% dos seus direitos de antena na transmissão de jogos para criar um Fundo de Fomento de todos as Modalidades Desportivas

**Comment by nuno-carneiro** [comment]
Olá Joana, tens de adicionar o ficheiro no Pull Request pf :)
