### ISSUE TITLE
CDU em vez de PCP + PEV

### ISSUE THREAD

**Issue by marado** [Politica-Para-Todos/pt-programas-legislativas-2019#6]
No README aparece o PCP e o PEV, mas a candidatura é da coligação CDU, pelo que me parece fazer mais sentido ter apenas uma entrada para a CDU do que estas duas.

**Comment by nuno-carneiro** [comment]
Pois, é um bom ponto @marado . Mas tenho ideia que eles apresentam programas eleitorais em separado não é? Ou existe um programa para CDU?

**Comment by DiogoM-Correia** [comment]
Apesar de ser candidatura da CDU, o programa eleitoral refere apenas o PCP. Não encontrei plano eleitoral dos Verdes por isso suponho que não tem para já ou nem vão ter.

**Comment by nuno-carneiro** [comment]
Já passei este feedback para as equipas de design e de dev, para considerarmos esta coligação. Mas de facto como os programas são separados, vou então fechar este issue. Obrigado pelo alerta @marado .
